# Minimal access control for the /api routes. This is a single shared
# credential (HTTP Basic Auth), generated by Terraform and stored in
# Secrets Manager - not a real per-user login system. It stops
# anonymous internet traffic (scanners, drive-by requests) from
# reading or writing patient records through the public CloudFront
# URL. For real multi-user auth, replace this with Cognito (already
# used in the companion NimbusDesk architecture) or a JWT-based login.

resource "random_password" "api_auth" {
  length  = 24
  special = false # kept URL/header-safe; this is a Basic Auth password, not typed by a human
}

resource "aws_secretsmanager_secret" "api_auth" {
  name                    = "${var.project_name}/api-auth"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "api_auth" {
  secret_id = aws_secretsmanager_secret.api_auth.id

  secret_string = jsonencode({
    username = "abchealthcare"
    password = random_password.api_auth.result
  })
}
